name: AWS EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest   # must be ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/comp7940-lab 
          git pull origin main
          docker stop hogwarts-bot || true
          docker rm hogwarts-bot || true
          docker build -t hogwarts-guide-bot:latest .
          docker run -d --name hogwarts-bot --restart=always -v $(pwd)/config.ini:/app/config.ini hogwarts-guide-bot:latest
          docker image prune -f
          EOF
